# Run tests using IATA NDC sample sandbox Kronos
label: ONDC

rest:
  url: http://prxy.airgateway.net:8080/gtwy/ndc/
  headers:
    Accept: application/xml
    Content-Type: application/xml
    AG-Authorization: key
    AG-Forwarded-Hosts: "*"

soap:
auth:

ndc:
  Document:
    Name: NDC Wrapper
    ReferenceVersion: "1.0"
  Party:
    Sender:
      ORA_Sender:
        AirlineID: C9
        Name: Kronos Air
        AgentUser:
          Name: TravelWadus
          Type: TravelManagementCompany
          PseudoCity: A4A
          AgentUserID: travelwadus
          IATA_Number: "00002004"
