rest:
  headers:
    Accept: application/xml
    Content-Type: application/xml
    AG-Authorization: 574f51531affed0643000001c5ac04f6e57e419c6cdc25ce998a2a8d
    AG-Forwarded-Hosts: "*"

server:
  url: http://prxy.airgateway.net:8080/gtwy/ndc/
  protocol: http
  server: prxy.airgateway.net:8080
  path: /gtwy/ndc
