rest:
  headers:
    Accept: application/xml
    Content-Type: application/xml
    AG-Authorization: secretkey
    AG-Forwarded-Hosts: "*"

server:
  url: http://prxy.airgateway.net:8080/gtwy/ndc/
  protocol: http
  server: prxy.airgateway.net:8080
  path: /gtwy/ndc

soap:
auth:

ndc:
  Document:
    Name: NDC Wrapper
    ReferenceVersion: "1.0"
  Party:
    Sender:
      ORA_Sender:
        AirlineID: C9
        Name: Kronos Air
        AgentUser:
          Name: TravelWadus
          Type: TravelManagementCompany
          PseudoCity: A4A
          AgentUserID: travelwadus
          IATA_Number: "00002004"
